version: '3.1'

services:
  db:
    image: postgres:alpine 
    restart: always
    environment:
      POSTGRES_PASSWORD: rooster
      POSTGRES_USER : rooster
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
       - ./home:/home
    ports:
      - 5432:5432
